# The name of the workflow.
name: Build and Deploy

# Run the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main

# This is the workflow that is being run.
jobs:
  build-and-test:
    # This is telling GitHub to run the workflow on the latest version of Ubuntu.
    runs-on: ubuntu-latest
    steps:

      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
          envkey_REACT_APP_FB_ID: ${{ vars.REACT_APP_FB_ID }}
          envkey_REACT_APP_IS_LOCAL: ${{ vars.REACT_APP_IS_LOCAL }}


      # Login to Docker Hub using credentials from repository secrets
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}  


      # Build a Docker image for the client application
      - name: Build Client Docker Image
        # Build image with tag ollah/ecomerce:client
        run: |
          docker build -t ollah/ecomerce:client-${{github.run_number}} .



      # Push the Docker images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push ollah/ecomerce:client-${{github.run_number}}
   # Job 2: Deploy to server
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
       # Use "appleboy/ssh-action" to deploy the image to the server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the image that was pushed to DockerHub above
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ecomerce:client-${{github.run_number}}

            # Stop and remove the current container (if any)
            docker stop ecomerce-client
            docker rm ecomerce-client

            # Run a new container with the image pulled above
            docker run -d -p 3000:3000 --name ecomerce-client ${{ secrets.DOCKERHUB_USERNAME }}/ecomerce:client-${{github.run_number}}
